language: php
dist: bionic

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor

install:
  - composer install --prefer-dist

script:
  - composer run lint
  - composer run test

notifications:
  email:
    on_success: never
